### ISSUE TITLE
not support color like rgb and predefined colors

### ISSUE THREAD

**Issue by JJJYY** [hzsrc/webpack-theme-color-replacer#1]
not support color, like `blue`, `rgb(0,0,0)`
and I got `#lue`, `#gb(0,0,0)`

**Comment by hzsrc** [comment]
Yes, not surported yet...
Need to change it to #rfb or #rrggbb

**Comment by hzsrc** [comment]
实现机制是文本替换，暂时支持不了英文颜色（容易替换错误）

**Comment by hzsrc** [comment]
补充下，blue、red这样的英文颜色不能替换，rgb(80, 120, 255)这样的颜色是可以的。把`80, 120, 255`也加到matchColors数组中即可。参考：https://github.com/hzsrc/webpack-theme-color-replacer/issues/18
