### ISSUE TITLE
output fileName 是否支持 hash 文件名

### ISSUE THREAD

**Issue by sendya** [hzsrc/webpack-theme-color-replacer#10]
在使用 cdn 时，时常因为文件名相同而无法获取新的文件内容。是否支持 `filename.[hash8].css` 的写法来输出文件

**Comment by hzsrc** [comment]
之前也想过这个问题，生成这个hash文件名倒是没问题，但因为在调用时需要在代码中引用这个文件名，目前没找到好的办法可以取到webpack生成的hash文件名，故没法实现

**Comment by hzsrc** [comment]
这两天研究了下，新版本已经通过脚本注入的方式实现了。后面看有没有更好的办法
