### ISSUE TITLE
WP_THEME_CONFIG is not defined ?

### ISSUE THREAD

**Issue by howiekang** [hzsrc/webpack-theme-color-replacer#106]
我在使用Antd Vue版本。但是每次切换主题的时候都会报错 WP_THEME_CONFIG is not defined。
1 WP_THEME_CONFIG 是在哪里配置的吗？
2 这个常量的作用?

![image](https://user-images.githubusercontent.com/29764501/175249947-b3128b24-dfc7-49a2-95f8-081a497ed629.png)
![image](https://user-images.githubusercontent.com/29764501/175250042-922f86a3-3430-427d-be45-af2d1a78676a.png)

**Comment by howiekang** [comment]
> 我在使用Antd Vue版本。但是每次切换主题的时候都会报错 WP_THEME_CONFIG is not defined。 1 WP_THEME_CONFIG 是在哪里配置的吗？ 2 这个常量的作用?
> 
> ![image](https://user-images.githubusercontent.com/29764501/175249947-b3128b24-dfc7-49a2-95f8-081a497ed629.png) ![image](https://user-images.githubusercontent.com/29764501/175250042-922f86a3-3430-427d-be45-af2d1a78676a.png)

@hzsrc

**Comment by samulle** [comment]
请问这个问题是怎么解决的啊？我这边也遇到了一样的问题。

**Comment by samulle** [comment]
![image](https://user-images.githubusercontent.com/10733931/187164729-c4074b13-5ed0-4be5-ae97-c0099ec1aacf.png)

**Comment by hzsrc** [comment]
是不是webpack里面没有用到webpack.DefinePlugin？加一下试试

**Comment by hzsrc** [comment]
或者能给一个重现办法？

**Comment by yangxyo** [comment]
> 是不是webpack里面没有用到webpack.DefinePlugin？加一下试试

请问在哪儿加哦，我用的 vue-cli5 也就是 webpack5

**Comment by hzsrc** [comment]
> > 是不是webpack里面没有用到webpack.DefinePlugin？加一下试试
> 
> 请问在哪儿加哦，我用的 vue-cli5 也就是 webpack5

参考样例项目

**Comment by gaollard** [comment]
same issue

**Comment by hzsrc** [comment]
我用webpack5用了几个项目，未发现报错。如果有问题另外再提issue吧，附上重现办法
