### ISSUE TITLE
何时支持typescript？

### ISSUE THREAD

**Issue by Alexanderwmc** [hzsrc/webpack-theme-color-replacer#11]
我从 `ant design pro` 升级到最新版本后，采用了 typescript ，vscode报错提示找不到本插件，发现是没有 .ts 格式的入口文件

**Comment by hzsrc** [comment]
有没有源码看下？应该支持的

**Comment by hzsrc** [comment]
你拉一下最新的ant design pro代码，支持的，前几天刚合并进去新版本。
