### ISSUE TITLE
1.4.3不再支持changeSelector了么?

### ISSUE THREAD

**Issue by windsonR** [hzsrc/webpack-theme-color-replacer#116]
yarn install了1.4.3之后, changeSelector不再生效,看了看提交记录,是把这个功能删掉了以后都不再支持了么?

**Comment by hzsrc** [comment]
没删。是有什么问题吗？

**Comment by windsonR** [comment]
就是debug的时候,始终不会进入我定义在changeSelector里的断点.

**Comment by hzsrc** [comment]
有效果吗？加一个console试一下。有时候chrome断点命中不准确的

**Comment by hzsrc** [comment]
你是下载到了github最新的代码了吗？最新的确实漏了，感谢提醒！这个应该属于1.4.4版本了，还没发布

**Comment by windsonR** [comment]
😂

**Comment by hzsrc** [comment]
已更新，请使用1.4.4

**Comment by windsonR** [comment]
好的.
