### ISSUE TITLE
 webpack-theme-color-replacer@@1.2.16

### ISSUE THREAD

**Issue by sophiehui99** [hzsrc/webpack-theme-color-replacer#12]
ThemeColorReplacer.getElementUISeries没有导出，导致之前安装这个包，使用这个方法的都报错了。

**Comment by hzsrc** [comment]
你好！之前设计的不太好，已经放到这里了：
const forElementUI = require('webpack-theme-color-replacer/forElementUI')

可参考[这个例子](https://github.com/hzsrc/vue-element-ui-scaffold-webpack4/blob/master/build/webpack.base.conf.js)
