### ISSUE TITLE
WP_THEME_CONFIG is not defined

### ISSUE THREAD

**Issue by rongyanping** [hzsrc/webpack-theme-color-replacer#123]
作者您好，我的项目中使用的webpack5.0.0， "webpack-theme-color-replacer": "1.4.5", 调用client.changer.changeColor的时候会报错 “WP_THEME_CONFIG is not defined” 请问是什么原因呢？

**Comment by hzsrc** [comment]
能否提供一个重现问题的环境，或者测试代码？

**Comment by MSOEPA** [comment]
你好 后面怎么解决？
