### ISSUE TITLE
最新版v1.4.7 build报错，回退至1.4.2 消失

### ISSUE THREAD

**Issue by lingjieding** [hzsrc/webpack-theme-color-replacer#124]
主要报错信息如下：
ERROR in style/theme-colors.theme.css
style/theme-colors.theme.css from Css Minimizer plugin
/Users/ddd/myproject/style/theme-colors.theme.css:29:1: Unknown word

**Comment by hzsrc** [comment]
/theme-colors.theme.css:29:1: Unknown word
能否提供下这里是什么内容？

**Comment by hzsrc** [comment]
尝试1.5.1
