### ISSUE TITLE
工程里面如果用了monaco-editor，构建的时候webpack-theme-color-replacer直接导致内存溢出了

### ISSUE THREAD

**Issue by dothin** [hzsrc/webpack-theme-color-replacer#131]
theme-color-replacer@1.5.2@webpack-theme-color-replacer/src/AssetsExtractor.js:83
            src.replace(CssCodeReg, (match, $1) => {
                ^

RangeError: Maximum call stack size exceeded

**Comment by dierbei** [comment]
@dothin 你解决了吗

**Comment by dierbei** [comment]
monaco edit 和 这个仓库冲突，需要修改一下依赖，我已经解决了这个问题，希望能对后来的朋友有帮助。

在依赖最后添加：
```json
"resolutions": {  "mockjs2/commander": "5.0.0"}
```

在 vue.config.js 中添加
![image](https://github.com/hzsrc/webpack-theme-color-replacer/assets/52097565/e0bf5bab-1295-445b-ae97-2b2b62e85ae3)

**Comment by IOTA233** [comment]
> monaco edit 和 这个仓库冲突，需要修改一下依赖，我已经解决了这个问题，希望能对后来的朋友有帮助。
> 
> 在依赖最后添加：
> 
> ```json
> "resolutions": {  "mockjs2/commander": "5.0.0"}
> ```
> 
> 在 vue.config.js 中添加 ![image](https://private-user-images.githubusercontent.com/52097565/322666659-e0bf5bab-1295-445b-ae97-2b2b62e85ae3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjE0NjYsIm5iZiI6MTcxNTA2MTE2NiwicGF0aCI6Ii81MjA5NzU2NS8zMjI2NjY2NTktZTBiZjViYWItMTI5NS00NDViLWFlOTctMmIyYjYyZTg1YWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA1NTI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NTkyYmY4Y2EzZGJmMDc3ZGIwMmU0MDFjZjVkZDYzNWQ1ZjkzYWQ4MjhhMzEyODc3YzhjZGJhMWNmNzA5ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PbvrDPWJLUyuXc0loTdE22SQW_O-WEY1WIPxwdCIvkw)

请问是怎么判断跟哪个包冲突？我没有使用monaco，也报这个错误了。node升级到18，replacer升级到1.52

**Comment by dierbei** [comment]
可以看看使用 install 命令是哪个包不兼容

**Comment by IOTA233** [comment]
> 可以看看使用 install 命令是哪个包不兼容

就是npm install吗？我把node_modules删了，重新下载，也没报不兼容……

**Comment by dierbei** [comment]
> 就是npm install吗？我把node_modules删了，重新下载，也没报不兼容……

我之前是 yarn install 会报错，安装失败。提示有的报版本不兼容
