### ISSUE TITLE
开发环境可以查看吗

### ISSUE THREAD

**Issue by Kiki-Q** [hzsrc/webpack-theme-color-replacer#2]
我按博主的操作了，但是没有效果，突然看到效果里面有句only for build not dev是只能在打包后看吗，那我想在开发的时候实时查看能吗？麻烦博主教教我

**Comment by newStu** [comment]
其实是可以的     这里的需要npm run build打包,生成对应的文件,后面只需要请求这个文件就可以替换颜色,相当于
.color-info{
   color:#ddd;
}
后面会把这个#ddd以及这个.color-info的类提取出来,然后放在一个theme-color.css的文件中,当我想换肤的时候我就请求theme-color.css这个文件,并且用方法匹配其中的#ddd的颜色换成你需要修改的颜色,然后用<style></style>标签追加在<head></head>里面,就覆盖了原先的样式了

**Comment by hzsrc** [comment]
是的，之前老版本的如@newStu 所说，需要先执行npm run build。
考虑到使用不方便，后来的升级版本，已经可以支持dev环境也查看了（从js中抓取css），无需再 npm run build。
