### ISSUE TITLE
production 模式下打包，window.__theme_COLOR_cfg 为 undefined

### ISSUE THREAD

**Issue by sendya** [hzsrc/webpack-theme-color-replacer#20]
最近调整了页面引入的方式，当时 prod 模式打包时，使用了 `externals` 进行一些依赖 JS 采用 cdn 加载，而不是直接编译到 `chunk-vendors`。

现在出现的现象是
![image](https://user-images.githubusercontent.com/5404542/64919255-e832da80-d7da-11e9-941f-029504655103.png)

本地调试时，不是使用 cdn 资源加载的，不会出现这种情况。下面是正常时候的截图
![image2](https://user-images.githubusercontent.com/5404542/64919265-faad1400-d7da-11e9-8956-fa2dc823d64b.png)

这是我之后改过的配置项文件
https://github.com/sendya/ant-design-pro-vue/blob/master/vue.config.js

**Comment by sendya** [comment]
debug 后得到的结果是。

`development` 运行时 `entryAssets` 的结果：
```
entryAssets [ 'app.js' ]
```

`production` 运行时 `entryAssets` 的结果：
```
entryAssets [ 'css/chunk-vendors.b00662ef.css',
  'js/chunk-vendors.d4bfce7e.js',
  'css/app.f36af825.css',
  'js/app.c9edc24e.js' ]
```

**Comment by sendya** [comment]
不好意思，引入 webpack 插件处理逻辑有问题。 问题已解决

**Comment by hzsrc** [comment]
刚看到，问题解决就好！我这工作太忙，较少能上来看
