### ISSUE TITLE
使用 less函数的文件无法生效

### ISSUE THREAD

**Issue by asvencoop** [hzsrc/webpack-theme-color-replacer#21]
hi,
在less 文件存在使用了一些颜色函数处理的颜色值，如下
```
color: fade(@primary-color, 80%); 
``` 
这种应该如何替换？

**Comment by hzsrc** [comment]
用js实现fade，然后将目标色也生成一个fade之后的颜色值，再调用替换过程。

**Comment by hzsrc** [comment]
刚试了下，这个fade生成的css最终颜色是类似 `rgba(24, 144, 255, .2)` 这样的，带了透明度，那就不是我之前说的方式了。而是采用与[这个](https://github.com/hzsrc/webpack-theme-color-replacer/issues/18)类似的方式解决。
