### ISSUE TITLE
能否支持编译出多个主题色文件

### ISSUE THREAD

**Issue by iota9star** [hzsrc/webpack-theme-color-replacer#22]
打包正式环境时，支持编译出多个主题色文件，而非动态编译，大佬看看这样能行吗

**Comment by hzsrc** [comment]
不太明白你说的意思，多个不同颜色的css文件吗，这样是不是会每次切换都要下载文件？目前方案没有动态编译啊，只是文本替换，只下载一次

**Comment by iota9star** [comment]
我最开始看过大佬你写的讲解原理文章，但后面没想到这茬，打包正式环境整了很久主题切换都没有生效，后面就脑补成了动态编译:yum:，尴尬的一匹:laughing:

问题现在已解决，原因是我现在打包完成后除了index.html外，其他文件会自动上传到七牛云，并替换所有的文件路径为七牛的路径，服务器只保留有一个index.html文件
![截图](https://user-images.githubusercontent.com/21272154/66250539-a7453a80-e776-11e9-8b11-ed16122c2c99.png)
而编译生成的theme css这里需要一个绝对路径提供给插件下载，之前仔细审查过代码，但没有考虑到文件的地址已经变成七牛的地址了，现在改成七牛配的地址就可以生效了，感谢大佬提供这个优秀的插件
