### ISSUE TITLE
newColor 重复值样式可能失效

### ISSUE THREAD

**Issue by pengfeiWang** [hzsrc/webpack-theme-color-replacer#27]
作者你好:
首先感谢提供这么好的插件
我在使用中发现一个问题, matchColors 是一个数组, 如果数组中出现重复的值的时候可能会对程序处理造成影响
我觉得是对比 oldColor 和 newColor 时, 在去处理匹配的样式时会出问题的
相同的色值, 不一定是相同的class, 是否可以使用 obj 键值对, 具名匹配 class 所对应的变量名称呢, 这样的话, 即使是重复的值也能精准对应到样式上

**Comment by hzsrc** [comment]
配置的色值可控制不要重复；重复了也没关系的；
这里只涉及替换颜色，不考虑class类名的。如果配置class，按class来替换颜色，配置会很复杂而且与css耦合紧密，那就完全是另一种处理了
