### ISSUE TITLE
提取CSS文件的时候不能提取rgba？

### ISSUE THREAD

**Issue by setWan** [hzsrc/webpack-theme-color-replacer#28]
您好，请问我提取文件的时候我设置的rgba(255, 104, 0, .65)不能提取出来？我现在的想法是可不可以加一个参数，让用户可以自定义提取规则

**Comment by hzsrc** [comment]
参考：https://github.com/hzsrc/webpack-theme-color-replacer/issues/18
色值配置：255, 104, 0
