### ISSUE TITLE
colors 重复值进行匹配替换问题

### ISSUE THREAD

**Issue by pengfeiWang** [hzsrc/webpack-theme-color-replacer#29]
```
// 主题1
var1 = '#1';
var2 = '#1';

.header {
  color: var1
}
.footer {
  color: var2
}
// 主题2
var1 = '#1';
var2 = '#2';

.header {
  color: var1
}
.footer {
  color: var2
}

```
// 切换主题时
replaceCssText 函数从当前样式中提取 CssText 进行匹配替换

假设

`oldColors[ #1, #1 ]`
`newColors[ #1, #2 ]`

循环 oldColors 第一次

CssText 匹配 `oldColors[ 0 ] = #1` 这时候会匹配到两项为 `#1` 的值
header footer 的 `color` 都是 `#1`
进行替换, 替换结果为 `newColors[ 0 ] = #1`

循环 `oldColors` 第二次 `var1` 与 `var2` 相同

CssText 匹配 `oldColors[ 1 ] = #1`, 这时候会匹配到两项为 `#1` 的值
进行替换, 替换结果为 `newColors[ 1 ] = #2`, 这里会把两项都替换掉
这时候 header footer 是相同的颜色了

cssText.replace(new RegExp(color.replace(/,/, ',\\s*'), 'ig'), newColors[t])

这结果并不是预期

两套主题, header footer 分别用不同颜色, 可能会出现如上描述情况

切换主题时会出现这样的情况, 编译首次执行未发现问题

**Comment by hzsrc** [comment]
是的，插件的原理，是最终css中的字符串替换。不管原来的less变量名是什么，甚至是没有引用变量名直接写死的颜色值，只要最终css颜色值一样，就会当作一种颜色来处理。所以，实现机制上决定了做不到将同一种颜色来作不同的处理。

对你得这种需求，可以考虑换种方式实现：只需定义var1和var2为2种差别很细微的颜色（比如将r、g、b中最大的一项数值+1，像#dc0456 => #dd0456）即可，通常肉眼分辨不出差别来。

**Comment by hzsrc** [comment]
对应确实颜色有差别的，此插件 提供一个 `changeSelector`方法配置，第2个参数，你可以修改util.rules中的值，定制你需要的css结果：
`js
            changeSelector(selector, util) { 
                if(select ==='.your-class' ) util.rules[0] = 'color: #abcdef'
                return selector
            },
`
