### ISSUE TITLE
能不能在打包的时候，直接就改变颜色

### ISSUE THREAD

**Issue by luanwulin** [hzsrc/webpack-theme-color-replacer#31]
项目需求是，在打包的时候直接就能更改颜色，所以能不能在webpack配置里面，加一个配置项，在打包阶段直接就把对应颜色替换完

**Comment by hzsrc** [comment]
打包时换色，可以通过sass或less的颜色变量来完美解决。
这个插件主要解决运行时动态换肤的问题的。打包时产生的颜色值分布在各个js或css文件中，很难替换，而且容易出错，还会影响源码映射。
