### ISSUE TITLE
大佬，请问该如何修改几个内置色呢？

### ISSUE THREAD

**Issue by MGsniper** [hzsrc/webpack-theme-color-replacer#33]
T-T大佬好，我想在ant-design-vue中使用主题切换。看了ant-design-vue-pro的案例，但看不太明白，该如何修改若干个指定的颜色呢
less+modifyVar的做法是这样
 ``` js
less: {
        modifyVars: {
          "@primary-color": "#f8c023",
          "@component-background": "#141414"
      }
}
```
color-replacer应该怎么写呢。

**Comment by hzsrc** [comment]
不清楚你说的意思。。如果是单色直接放matchColors里面，如果是色系先生成色系。请参考用例，分析源码尝试

**Comment by MGsniper** [comment]
之前源代码看漏了一段，走弯路了，现在问题解决了。
分享一下，关键代码片段吧。（核心就是 matchColors和newColors一一配对）
webpack plugin配置：
```js
 //  要替换的原色
  matchColors: getAntdSerials("#f8c023")
    .concat(getAntdSerials("#141414")) // 匹配色系
    .concat(["#000"]), //  匹配单色
```
定义changeColor函数：
```js
changeColor(newColors) {
    var newColorArr = [];
    newColors.forEach((color, index) => {
       // 改色系
        newColorArr = newColorArr.concat(this.getAntdSerials(color));
      //  改单色
         newColorArr.push(color);
       }
    });
    var options = {
      newColors: newColorArr, // new colors array, one-to-one corresponde with `matchColors`
      changeUrl(cssUrl) {
        return `/${cssUrl}`; // while router is not `hash` mode, it needs absolute path
      }
    };
    return client.changer.changeColor(options, Promise);
  }
```

**Comment by hzsrc** [comment]
> 之前源代码看漏了一段，走弯路了，现在问题解决了。
> 分享一下，关键代码片段吧。（核心就是 matchColors和newColors一一配对）
> webpack plugin配置：
> 
> ```js
>  //  要替换的原色
>   matchColors: getAntdSerials("#f8c023")
>     .concat(getAntdSerials("#141414")) // 匹配色系
>     .concat(["#000"]), //  匹配单色
> ```
> 
> 定义changeColor函数：
> 
> ```js
> changeColor(newColors) {
>     var newColorArr = [];
>     newColors.forEach((color, index) => {
>        // 改色系
>         newColorArr = newColorArr.concat(this.getAntdSerials(color));
>       //  改单色
>          newColorArr.push(color);
>        }
>     });
>     var options = {
>       newColors: newColorArr, // new colors array, one-to-one corresponde with `matchColors`
>       changeUrl(cssUrl) {
>         return `/${cssUrl}`; // while router is not `hash` mode, it needs absolute path
>       }
>     };
>     return client.changer.changeColor(options, Promise);
>   }
> ```

是的，赞一个！

**Comment by MGsniper** [comment]
>..<嘤嘤嘤
