### ISSUE TITLE
建议将options 的cssUrl 支持一下数组

### ISSUE THREAD

**Issue by yangdongMC** [hzsrc/webpack-theme-color-replacer#34]
在一些较为特别的场景下，每个模块对应着自己的css 文件，然而这些文件又不能合并成一个写在一起：

&emsp;&emsp;那么这个时候，做动态换肤时，首先在webpack 处理时就存在会生成多个theme-color.css,但是在选完颜色切换时，由于cssUrl 传入的是一个字符串，在getCssText 这个方法只会处理一次，就造成了只会对最后一个theme-color.css 进行换肤，原因是theme_COLOR_config.url 就保存了最后一次生成的url 地址。

&emsp;&emsp;建议：支持一下数组
`````
themeColorchanger.js

// getCssText(cssUrl, setCssTo, resolve, reject)
   if(cssUrl.length){
         cssUrl.forEach((item)=>{
               getCssText(item, setCssTo, resolve, reject)
          })
   }


`````

**Comment by hzsrc** [comment]
如果是数组，这里的resolve不好处理。
我觉得你这个需求应该可以通过options.changeUrl函数来处理？不同的模块，你可以控制changeUrl返回不同的theme-color-xxx.css地址，切换这个模块主题色
