### ISSUE TITLE
引入webpack-cos-plugins插件时候，报错

### ISSUE THREAD

**Issue by wh469012917** [hzsrc/webpack-theme-color-replacer#35]
会报错这个：
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_isThemeJsInjected' of undefined
```

**Comment by wh469012917** [comment]
issue提供的信息可能对于排查问题有限，如果有需要其他信息可以可以回复， 不要看到了当作没看到不回复，万分感谢~

**Comment by hzsrc** [comment]
@wh469012917 如何重现？

**Comment by hzsrc** [comment]
我这没重现，但我把判断加上了， webpack-theme-color-replacer@1.3.4

**Comment by wh469012917** [comment]
@hzsrc 引入webpack-cos-plugins插件, 然后配置上传完成后删除本地文件, 在删除本地文件的时候就会出现这个问题 Cannot read property '_isThemeJsInjected' of undefined

**Comment by hzsrc** [comment]
npm ERR! code E404
npm ERR! 404 Not Found: webpack-cos-plugins@latest

你用webpack-theme-color-replacer@1.3.4 试试，已经加上undefined判断，应该不会报你说的错误了
