### ISSUE TITLE
vue打包后的umd.js文件最后有window.__theme_COLOR_cfg

### ISSUE THREAD

**Issue by liujianchaogit** [hzsrc/webpack-theme-color-replacer#37]
vue打包后的umd.js文件最后有
window.__theme_COLOR_cfg={"url":"css/theme-colors-2ac47ff0.css","colors":["#1890ff","#2f9bff","#46a6ff","#5db1ff","#74bcff","#8cc8ff","#a3d3ff","#badeff","#d1e9ff","#e6f7ff","#bae7ff","#91d5ff","#69c0ff","#40a9ff","#1890ff","#096dd9","#0050b3","#003a8c","#002766","24,144,255"]};

如果第三方项目使用这个umd.js文件，changeColor无法替换颜色，如果把这行注释掉项目就可以替换颜色了，请问是为什么

**Comment by hzsrc** [comment]
这个是自动注入的颜色值，可省去配置的麻烦。如果此项目是给第三方项目使用，此项目就不要用这个插件了，而是由此项目的使用方来用它。
