### ISSUE TITLE
无法找到模块的申明文件

### ISSUE THREAD

**Issue by lichnow** [hzsrc/webpack-theme-color-replacer#38]
vue-cli4.x报错提示如下(js环境，不是ts)
```
This dependency was not found:

* webpack-theme-color-replacer/client in ./src/components/SettingDrawer/themeColor.js

To install it, you can run: npm install --save webpack-theme-color-replacer/client
```

**Comment by hzsrc** [comment]
安装了webpack-theme-color-replacer吗？
如果有安装，请提供下重现步骤。。

**Comment by NHZEX** [comment]
> 安装了webpack-theme-color-replacer吗？
> 如果有安装，请提供下重现步骤。。

遇到一样的问题

使用 [d2-projects/d2-admin-start-kit](https://github.com/d2-projects/d2-admin-start-kit) 开发项目  
安装后依赖版本为 webpack-theme-color-replacer 1.3.3，使用 yarn upgrade 升级到 1.3.4 后出现一样的错误，降级到 1.3.3 正常。

**Comment by foxcharon** [comment]
> 安装了webpack-theme-color-replacer吗？
> 如果有安装，请提供下重现步骤。。

遇到一样的问题。
使用 [ant-design/ant-design-pro](https://github.com/ant-design/ant-design-pro) 开发项目
安装后依赖版本为 webpack-theme-color-replacer 1.3.4，无法运行项目，报错与上面相同。
降级到 1.3.3 正常。

**Comment by kidonng** [comment]
上面两条评论表明 1.3.3 到 1.3.4 之间肯定发生了什么。

https://github.com/hzsrc/webpack-theme-color-replacer/commit/aa64ed13d8b75a536c38a4254b50209e40269782#diff-ab14ab087e6e4fbde2c37b103d65edc1
https://github.com/hzsrc/webpack-theme-color-replacer/commit/82f7e3988c4e601df68867cd3f77857b2a193a39#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

这两处文件改动的第一行都有不可见字符的变化，本地 diff 一下可以发现是 `<EF><BB><BF>` 也就是 [BOM](https://stackoverflow.com/a/44098350)。

![image](https://user-images.githubusercontent.com/44045911/76007405-f58a7f80-5f48-11ea-8aa4-118946baaae7.png)

这两处改动可能干扰了 Node 或者 Webpack 的模块解析，如果我的猜测为真，各位把这个模块的 `package.json` 重新保存一下就可以了。我这里无法验证，有劳各位了。

**Comment by NHZEX** [comment]
> 上面两条评论表明 1.3.3 到 1.3.4 之间肯定发生了什么。
> 
> [aa64ed1#diff-ab14ab087e6e4fbde2c37b103d65edc1](https://github.com/hzsrc/webpack-theme-color-replacer/commit/aa64ed13d8b75a536c38a4254b50209e40269782#diff-ab14ab087e6e4fbde2c37b103d65edc1)
> [82f7e39#diff-b9cfc7f2cdf78a7f4b91a753d10865a2](https://github.com/hzsrc/webpack-theme-color-replacer/commit/82f7e3988c4e601df68867cd3f77857b2a193a39#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)
> 
> 这两处文件改动的第一行都有不可见字符的变化，本地 diff 一下可以发现是 `<EF><BB><BF>` 也就是 [BOM](https://stackoverflow.com/a/44098350)。
> 
> ![image](https://user-images.githubusercontent.com/44045911/76007405-f58a7f80-5f48-11ea-8aa4-118946baaae7.png)
> 
> 这两处改动可能干扰了 Node 或者 Webpack 的模块解析，如果我的猜测为真，各位把这个模块的 `package.json` 和 `src/Handler.js` 重新保存一下就可以了。我这里无法验证，有劳各位了。
> 
> 顺便提一下关联的 #36 #39。

验证成功，应该是BOM的问题了

**Comment by hzsrc** [comment]
我错了，之前在家直接用notepad编辑了。。测试也不报错
现已修复为1.3.5版本，谢谢！
