### ISSUE TITLE
Why can't I install the dependency ?

### ISSUE THREAD

**Issue by mateuzor** [hzsrc/webpack-theme-color-replacer#39]
**[HELP] I got the following error while trying to run the project using **yarn start****

webpack-theme-color-replacer/client in ./src/components/SettingDrawer/themeCol
orClient.js

Then I got a message telling to run the lib using this command below, which I did

**npm install --save webpack-theme-color-replacer/client**

but I got this message: 

$ npm install --save webpack-theme-color-replacer/client
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\mingw64\bin\git.EXE ls-remote -h -t ssh://git@github.com/webpack-theme-color-replacer/client.git
npm ERR!
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Matheus.Ramos\AppData\Roaming\npm-cache\_logs\2020-03-04T20_17_30_680Z-debug.log

**Any solution ?**

**Comment by hzsrc** [comment]
pls try `npm install webpack-theme-color-replace@latest`

**Comment by mateuzor** [comment]
Still with an error
$ npm install webpack-theme-color-replace@latest
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/webpack-theme-color-replace - Not found
npm ERR! 404
npm ERR! 404  'webpack-theme-color-replace@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Matheus.Ramos\AppData\Roaming\npm-cache\_logs\2020-03-09T19_29_42_538Z-debug.log

**Comment by hzsrc** [comment]
Sorry for that, there is a `r` missed, it's: `npm install webpack-theme-color-replacer@latest`
