### ISSUE TITLE
包内部路径问题(Package internal path problem)???

### ISSUE THREAD

**Issue by newStu** [hzsrc/webpack-theme-color-replacer#4]
![img1](https://user-images.githubusercontent.com/31842230/54109123-bd755d00-4418-11e9-80d4-358b6236a422.png)
![img2](https://user-images.githubusercontent.com/31842230/54109124-bd755d00-4418-11e9-8b35-bb5c78246dbc.png)
在ThemeColorReplacer的构造函数中fileName的路径可以使用options.fileName,不需要使用固定地址,但好像没有对全局造成影响 @hzsrc

**Comment by hzsrc** [comment]
这个是用Object.assign取默认值。如果options.fileName没有传入，就取这个默认的

**Comment by newStu** [comment]
哦哦,谢谢,明白了

**Comment by qyb** [comment]
这里可能有一个问题，就是输出路径的时候，没有考虑到 publicPath 设定的影响...

**Comment by newStu** [comment]
是说的是默认打包路径吗????

如果是可以配成这样:public/site_theme/theme-colors.css

![image](https://user-images.githubusercontent.com/31842230/59988695-9ca2e180-966e-11e9-8a03-877575c9b990.png)


我只是很感兴趣,问问,就问问,嘻嘻

**Comment by hzsrc** [comment]
用相对路径可以的。要用绝对路径的话，客户端在changeUrl里面可以配置

**Comment by newStu** [comment]
> 用相对路径可以的。要用绝对路径的话，客户端在changeUrl里面可以配置

哦哦,看到了

**Comment by qyb** [comment]
我是从 https://github.com/sendya/ant-design-pro-vue/issues/295 这里反馈的问题过来的；暂时不影响我的开发过程，所以没有细究。它那里缺省的用法就是 fileName: 'css/theme-colors-[contenthash:8].css'. 
 
我对 webpack-dev-server 的用法和一般前端开发不一样，我是后端开发出身，浏览器入口是我 realserver 
的服务端口，它静态资源比如 app.js 引用 webpack-dev-server （所以我不需要 proxy 设置，但得修改 header: CORS 之类），因此 publicPath 需要配置到 webpack-dev-server 所在的端口，否则路径是相对当前页面即我的 realserver 服务端口的..

现在碰到的问题就是，webpack 自己生成的资源路径都是正确的了，但是这个 theme-colors-hash8.css 的路径仍然是相对当前 HTML baseurl 的. 而不是相对 module.exports 定义的 publicPath
