### ISSUE TITLE
vue-element-admin，production模式，加载的css文件路径为undefined

### ISSUE THREAD

**Issue by naclank** [hzsrc/webpack-theme-color-replacer#40]
vue-element-admin用的是[https://github.com/hzsrc/vue-element-admin](https://github.com/hzsrc/vue-element-admin)
dev模式可以正常切换颜色，production模式切换颜色时会去加载一个错误的路径：http://localhost/undefined

dev模式：
![1](https://user-images.githubusercontent.com/10046244/78651723-4e0bbe80-78f3-11ea-8c83-450da66c4df2.png)
![image](https://user-images.githubusercontent.com/10046244/78652031-bf4b7180-78f3-11ea-9558-79d672f23931.png)

production模式：
![image](https://user-images.githubusercontent.com/10046244/78651973-a773ed80-78f3-11ea-91ba-8fb84b7384b9.png)
![image](https://user-images.githubusercontent.com/10046244/78652085-d4280500-78f3-11ea-976f-9c83d579038f.png)

**Comment by hzsrc** [comment]
可能与webpack配置有关。如何能重现这个问题？

**Comment by naclank** [comment]
@hzsrc 
[https://github.com/hzsrc/vue-element-admin](https://github.com/hzsrc/vue-element-admin)
这个工程，没有做任何修改，npm run build:prod打包后，放在nginx下，就可以复现这个问题

**Comment by hzsrc** [comment]
Hi, this bug has been fixed, please use this version: 

`npm i webpack-theme-color-replacer@1.3.8`

Thanks for reporting!

**Comment by naclank** [comment]
@hzsrc 问题已解决，感谢大佬！
