### ISSUE TITLE
打包时在window上设置变量的代码被打到了runtime-thunk里导致window变量未正确设置

### ISSUE THREAD

**Issue by BarneyZhao** [hzsrc/webpack-theme-color-replacer#42]
在webpack构建中设置了
```js
optimization: {
  runtimeChunk: {
    name: (entrypoint) => `runtime-${entrypoint.name}`,
  },
}
```
打包后代码 `window.__theme_COLOR_cfg={"url":"css/theme-colors-60ef0023.css","colors":["#1890ff"]};` 插入到了 runtime-thunk 的代码中，不会在应用运行时加载，导致window变量没有设置

目前临时修改 node_modules 中的源码解决了问题
/webpack-theme-color-replacer/src/Handler.js : 57
```js
if (assetName.slice(-3) === '.js' && assetName.indexOf('manifest.') === -1 && assetName.indexOf('runtime-') === -1) { //
    // ...                  
  }
```

**Comment by hzsrc** [comment]
目前是根据文件名包含“manifest.”来识别的。自定义的runtime名称确实是一个问题，如何识别一个js文件是不是runtimeChunk？

**Comment by hzsrc** [comment]
可否改成这样一下？
````js
optimization: {
  runtimeChunk: {
    name: (entrypoint) => `manifest.${entrypoint.name}`,
  },
}
````
