### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'split' of undefined at getCssText (themeColorChanger.js?b146:49)

### ISSUE THREAD

**Issue by Virgil-N** [hzsrc/webpack-theme-color-replacer#43]
我用的vue cli3，按照教程配置的，不知道为什么报这个错

**Comment by hzsrc** [comment]
我这没发现，不过我根据你的报错提示，调整了一下，你可以更新再试一下看：webpack-theme-color-replacer@1.3.9

**Comment by Virgil-N** [comment]
> 我这没发现，不过我根据你的报错提示，调整了一下，你可以更新再试一下看：webpack-theme-color-replacer@1.3.9

好的
