### ISSUE TITLE
client 上切换颜色后，切换回默认颜色 isSameArr 校验全相同

### ISSUE THREAD

**Issue by sendya** [hzsrc/webpack-theme-color-replacer#45]
`theme_COLOR_config.colors` 的 `值` 始终不变，导致切换到其他颜色后，切换到默认色直接不更新 css

**Comment by hzsrc** [comment]
你好，这个问题修复了：webpack-theme-color-replacer@1.3.11

**Comment by sendya** [comment]
好的，谢谢
