### ISSUE TITLE
vuecli2下生成的css内容为空

### ISSUE THREAD

**Issue by 781499682ll** [hzsrc/webpack-theme-color-replacer#46]
复现方法，使用vue-cli2 init 一个新项目   webpack3
安装和使用方式同  https://github.com/hzsrc/vue-element-ui-scaffold-webpack4  
build出来是ok的，但是run dev就
Extracted theme color css content length: 0  
麻烦大佬解答下为啥会出现这种情况，如何操作才能正常使用

**Comment by hzsrc** [comment]
fixed:  webpack-theme-color-replacer@1.3.12

**Comment by 781499682ll** [comment]
thanks
