### ISSUE TITLE
css 动画 bug

### ISSUE THREAD

**Issue by iczer** [hzsrc/webpack-theme-color-replacer#49]
感谢您的贡献。

最近的一个项目中使用了您的库，发现下面一个问题
rgba 色值模式下，css 动画 `translate3d(x,y,z)` 、`scale3d(x,y,z)` ...等，(x，y, z) 可能会被当做rgb色值替换。

希望作者能修复下这个bug，
感谢！:star2:

**Comment by hzsrc** [comment]
正好碰到(x,y,z)与你需要匹配的颜色值相同了吗？这么巧合啊！
这种情况应该比较少见，建议将(x，y, z) 的值略微变一变，使二者不再相同。比如scale3d(100, 80, 30) 改为 scale3d(100.0, 80.001, 30)  ，看是否能解决？

**Comment by iczer** [comment]
因为用到了纯黑白色，然后很多动画里面有初始帧 transform3d(0, 0, 0)，这个不太好避免。
不过现在是通过 resloveCss 钩子对动画类的class 单独处理解决了问题。
感谢建议
