### ISSUE TITLE
为啥button hover的样式里面color还是原色？

### ISSUE THREAD

**Issue by FlowerCheng123** [hzsrc/webpack-theme-color-replacer#5]

**Comment by hzsrc** [comment]
不清楚你说的是哪里？请提供更多信息及截图，或是jsfiddler之类的在线例子？
如果是element-ui那个按钮，那应该是这个原因：
[https://github.com/hzsrc/vue-element-ui-scaffold-webpack4/blob/master/src/css/override.scss](https://github.com/hzsrc/vue-element-ui-scaffold-webpack4/blob/master/src/css/override.scss)

**Comment by hzsrc** [comment]
> 不清楚你说的是哪里？请提供更多信息及截图，或是jsfiddler之类的在线例子？
> 如果是element-ui那个按钮，那应该是这个原因：
> https://github.com/hzsrc/vue-element-ui-scaffold-webpack4/blob/master/src/css/override.scss

之前这种方式欠优雅，不好维护。刚才花时间重新设计了方案，针对element-ui采用这个方式：
[build/webpack.base.conf.js](https://github.com/hzsrc/vue-element-ui-scaffold-webpack4/blob/master/build/webpack.base.conf.js)
效果见[这里](http://test.hz300.com/webpack4/themeColor.html)：
