### ISSUE TITLE
主题颜色没有加载出来，apply()没有执行

### ISSUE THREAD

**Issue by teng0226** [hzsrc/webpack-theme-color-replacer#50]
class ThemeColorReplacer {
    constructor(options) {
        this.handler = new Handler(options)
    }

    getBinder(compiler, event) {
        return compiler.hooks
            ? compiler.hooks[event].tapAsync.bind(compiler.hooks[event], 'ThemeColorReplacer')
            : compiler.plugin.bind(compiler, event)
    }

    apply(compiler) {
        console.log('compiler')
        // this.getBinder(compiler, 'compilation')((compilation) => {
        //   this.getBinder(compilation, 'html-webpack-plugin-before-html-processing')((htmlPluginData, callback) => {
        //     debugger
        //   })
        // });
        this.getBinder(compiler, 'emit')((compilation, callback) => {
            this.handler.handle(compilation)
            callback()
        });
    }
}

**Comment by hzsrc** [comment]
webpack什么版本？怎样重现这个问题？
