### ISSUE TITLE
vue-cli3使用compression-webpack-plugin插件后替换颜色失效

### ISSUE THREAD

**Issue by lkail** [hzsrc/webpack-theme-color-replacer#51]
vue.config.js配置：
chainWebpack: config => {
    // css、js压缩
    if (!isDev) {
      config.plugin('compressionPlugin').use(new CompressionPlugin({
        test: /\.(js|html|css)$/, // 匹配文件名
        threshold: 1024, // 对超过1k的数据压缩
        deleteOriginalAssets: false // 不删除源文件
      }))
    }
  }

**Comment by hzsrc** [comment]
webpack自带了压缩，不需要这个插件吧
