### ISSUE TITLE
当第一个打开的页面是重定向进来的时候.不能正确请求到css文件

### ISSUE THREAD

**Issue by opop007** [hzsrc/webpack-theme-color-replacer#52]
`
  path: '/data',
  name: 'data',
  redirect: '/data/dataCell',
`
比如当我的路由如上所示的时候.请求的地址因为是相对地址. 就会变成 
`http://host/data/css/theme-colors.[contenthash:8].css`
而不是 
`http://host/css/theme-colors.[contenthash:8].css`
这时候加载不到正确的文件的时候.就会修改颜色失败了

把 themeColorChanger.js文件请求css文件的那一段
`xhr.open('GET',  url)`
改成
`xhr.open('GET', '/' + url)`
就能避免这个问题.

**Comment by hzsrc** [comment]
使用option.changeUrl回调函数解决。请参考首页文档
