### ISSUE TITLE
能够实现 antd default和dark主题的切换吗

### ISSUE THREAD

**Issue by soonyh** [hzsrc/webpack-theme-color-replacer#53]
问题一：切换前，2处都是`#fff`，但切换之后要求：`#000`和`#141414`，可以实现吗？

before

```less
@body-background: #fff;
@component-background: #fff;
```

after

```less
  '@body-background': '#000',
  '@component-background': '#141414',
```

> 插件的原理是：在changeColor时，根据`newColors` 数组中的顺序依序替换`matchColors`中注册的颜色。我的理解对吗？

问题二：如果两个主题，除了颜色之外，还存在其他的差异（比如padding, solid等） 插件能支撑的了吗?

@hzsrc  求助 求助

**Comment by hzsrc** [comment]
1、实现不了。相同的颜色是相同的替换处理。你可以一个用#fff，一个用#ffffff。
2、只会替换主题色，其他样式保持不动。
