### ISSUE TITLE
不用ui框架如何修改主题色呢？

### ISSUE THREAD

**Issue by yjk0306** [hzsrc/webpack-theme-color-replacer#54]
普通的项目，不使用elementui 如何使用呢？

**Comment by yjk0306** [comment]
`  // vue-config-js
		config.plugin('webpack-theme-color-replacer')
    .use(ThemeColorReplacer)
    .tap(options => {
      options[0] = {
        fileName: 'css/theme-colors-[contenthash:8].css',
        matchColors: [ '#409eff', '#efefef'], //自定义颜色 
        // changeSelector: forElementUI.changeSelector,
        isJsUgly: process.env.NODE_ENV !== 'development'
      }
      return options
    })

 // 方法页面
import client from 'webpack-theme-color-replacer/client'
import appConfig from './config.js'

export let curColor = appConfig.themeColor

// 动态切换主题色
export function changeThemeColor(newColor) {
    const options = {
        newColors: ['#409eff', '#efefef'],
    }
    return client.changer.changeColor(options, Promise)
        .then(t => {
            curColor = newColor
            localStorage.setItem('theme_color', curColor)
            console.log('Theme colors changed!')
        });
}

export function initThemeColor() {
    const savedColor = localStorage.getItem('theme_color')
    if (savedColor) {
        curColor = savedColor
        changeThemeColor(savedColor)
    }
}

`

**Comment by hzsrc** [comment]
这里ElementUI只是举例。其他一些常见项目我也有做了例子，可供参考：
https://segmentfault.com/a/1190000016061608
