### ISSUE TITLE
fileName参数能否支持绝对路径

### ISSUE THREAD

**Issue by ZthStudy** [hzsrc/webpack-theme-color-replacer#55]
fileName参数默认前缀会加上文件相对路径，服务器静态资源路径可能并不在此路径上，导致nginx会多出配置，如果是微前端会增加不少。

**Comment by hzsrc** [comment]
我查了代码，编译时fileName调用的是compilation.getPath(fileName, { contentHash })，似乎并没有显式加上当前路径。
我看你的意思应该是运行时的路径吧？如果是这样，应该通过 changeUrl函数来解决问题

**Comment by ZthStudy** [comment]
是的，已用changeUrl解决，谢谢！
