### ISSUE TITLE
在main.js中调用client.changer.changeColor 时 changeUrl中的url不是最新的build的hash地址

### ISSUE THREAD

**Issue by wangxv** [hzsrc/webpack-theme-color-replacer#57]
在main.js中调用client.changer.changeColor 时 changeUrl中的url不是最新的build的hash地址
window.__theme_COLOR_cfg的地址是之前打包的hash的地址
![image](https://user-images.githubusercontent.com/30195186/101016068-3d573980-35a3-11eb-9aa8-5eb2e7bc4287.png)
![image](https://user-images.githubusercontent.com/30195186/101016578-f289f180-35a3-11eb-9fc3-89396a25a4be.png)
@hzsrc

**Comment by hzsrc** [comment]
图挂了，显示不出

**Comment by hzsrc** [comment]
你的项目是否是有多个entry的js在同一个页面运行？并且老版本的js在后面运行了

**Comment by hzsrc** [comment]
如果有多个使用此插件的webpack项目打包的js，可能会有变量冲突。
还有一种可能，检查下是不是html引用的js文件是老版本或者使用缓存中的老代码。window.__theme_COLOR_cfg是在第一个入口js文件中注入的，检查这个文件是否缓存了

**Comment by debbydeng** [comment]
只有一个entry。看你们源码，是在第一个js文件的hash值生成后注入了css, css改变并不会改变这个js文件的hash值，所以文件名还是之前的文件名，根据浏览器缓存策略，浏览器拉取的文件会是之前的老文件，造成了bug

**Comment by hzsrc** [comment]
![image](https://user-images.githubusercontent.com/19581578/104021147-44541600-51f9-11eb-9732-3d7b0da5dbe2.png)
查了源码，__theme_COLOR_cfg.url中的contenthash，是来自css输出的，css输出如果有变化，contenthash应该会变啊。不太明白你说的“之前的老文件”是指？能否详细说下哪个地方代码有问题

**Comment by huaidan5859** [comment]
> 如果有多个使用此插件的webpack项目打包的js，可能会有变量冲突。
> 还有一种可能，检查下是不是html引用的js文件是老版本或者使用缓存中的老代码。window.__theme_COLOR_cfg是在第一个入口js文件中注入的，检查这个文件是否缓存了

如果有多个使用此插件的webpack项目打包的js， 需要怎么处理呢？
