### ISSUE TITLE
Element-ui部分组件替换颜色失败

### ISSUE THREAD

**Issue by wb8940336** [hzsrc/webpack-theme-color-replacer#58]
截至目前发现的，
1.Pagination 分页带背景的 background
2.Tag 标签  effect=dark
以上2个都是带背景的，有时候文字颜色和背景颜色一样了，有时候替换出来的颜色值是undefined

**Comment by hzsrc** [comment]
如何重现问题？能否截几个图看下
https://hzsrc-vue-webpack4-elementui.netlify.app/themecolor 这里我看是有效的

**Comment by wb8940336** [comment]
1.Pagination 添加background   
2.Tag 标签 effect=dark 模式下
这是不是上传不了图片

**Comment by wb8940336** [comment]
[https://imgchr.com/i/swTBq0](url)
[https://imgchr.com/i/swThs1](url)
[https://imgchr.com/i/swTIZ6](url)

**Comment by hzsrc** [comment]
你好，这个是css优先级导致的，已经修复了： webpack-theme-color-replacer@1.3.15
如果不想升级，也可以手动修改changeSelector函数解决。
![image](https://user-images.githubusercontent.com/19581578/104832597-278ca200-58cd-11eb-9b22-ae9928f83bb2.png)

**Comment by wb8940336** [comment]
还有点问题就是  调用changeColor的时候是要做判断  如果当前颜色已经是主题色，再调用changeColor方法修改同颜色  就会出现color:undefind,  这样就会导致后面的 所有替换颜色都会失败

情景：进项目的时候调用一次changeColor  其实这时候要修改的颜色跟主题色是一致的

**Comment by hzsrc** [comment]
> 还有个问题 主题色#3438D3 和 #3438d3 是不相等的么，是没有忽略大小写 默认颜色是#3438d3 替换为#3438D3 就会出错

好像没碰到过？匹配颜色是忽略大小写的
