### ISSUE TITLE
关于生成theme-colors.css文件的勾子的问题

### ISSUE THREAD

**Issue by FlowerCheng123** [hzsrc/webpack-theme-color-replacer#6]
hello,
     我发现一个问题，不知道是不是跟我的配置有关，
<img width="955" alt="屏幕快照 2019-04-04 下午7 10 45" src="https://user-images.githubusercontent.com/8719916/55551486-82133900-570d-11e9-82cb-3dc91786cd9c.png">
    在勾子emit的时候生成theme-colors.css文件在我的生产环境下有问题，所以我怀疑是不是在生成文件的时机不对，我把emit改成了afterEmit，就好了

**Comment by hzsrc** [comment]
@FlowerCheng123 你是直接引用了css/theme-colors.css这个文件吗？我看貌似是postcss把它当作源文件处理了。这个文件是运行时动态下载的，不需要直接引用的。

**Comment by FlowerCheng123** [comment]
这个也是我奇怪的地方，我的项目里面并咩有用到theme-colors.css的文件，我知道这是一个编译时的一个文件，postcss理论上是不会去编译的，但是我用了pxtorem这个插件，需要对theme-colors这个文件进行处理估计，所以我这边做个一个讨巧，把emit改成了afterEmit就好了，所以我猜是不是插件间执行顺序的问题

**Comment by hzsrc** [comment]
afterEmit没有测试过，会不会有其他问题呢？如果你测了没问题，可以拉一个PR合并进来
