### ISSUE TITLE
vue ssr下会报错 window is not defined

### ISSUE THREAD

**Issue by addcky** [hzsrc/webpack-theme-color-replacer#61]
![20210125104304](https://user-images.githubusercontent.com/20477361/105655010-33461d00-5efa-11eb-9b56-90d0369e5978.jpg)

**Comment by hzsrc** [comment]
ssr没有测过。。有没有问题截图或者修复建议？

**Comment by hzsrc** [comment]
已将window改为this，看下是否兼容？

**Comment by hzsrc** [comment]
若还有问题另提
