### ISSUE TITLE
webpack5使用插件报错

### ISSUE THREAD

**Issue by binjie09** [hzsrc/webpack-theme-color-replacer#63]
升级webpack5后调试发现entryAssets[i]这个东西会是个对象，然后编译会报错。
![image](https://user-images.githubusercontent.com/18377378/108339847-e44a8980-7212-11eb-99e2-e663e27790ad.png)

**Comment by liuc96** [comment]
我也遇到这个问题了

**Comment by hzsrc** [comment]
合并、发布好了，请用 1.3.16 版本。谢谢
