### ISSUE TITLE
webpack5中，js中的css样式丢失

### ISSUE THREAD

**Issue by liuc96** [hzsrc/webpack-theme-color-replacer#65]
webpack: 5.23.0
webpack-cli: 3.3.12
node: 14.0.0

问题：
![image](https://user-images.githubusercontent.com/33923419/108589271-9d869c00-7398-11eb-9b9c-a78078cef7e4.png)
js中的css样式没截取到
怀疑webpack5 loader的逻辑改了

临时方案：
用`mini-css-extract-plugin`把css分离出来

**Comment by hzsrc** [comment]
css-loader的版本是多少？有可能跟它有关

**Comment by liuc96** [comment]
> css-loader的版本是多少？有可能跟它有关

webpack4 3.4.2
webpack5 3.6.0
升级5的时候 我也没敢动其他依赖包的大版本 就怕出问题

**Comment by hzsrc** [comment]
我用css-loader@3.6.0的测了没重现问题。
我另一个项目用了"css-loader": "^5.1.1"，之前有问题，现已修复了。要么你升级一下到5.1 ？
项目见：https://github.com/hzsrc/vue-element-ui-scaffold-webpack4

**Comment by hzsrc** [comment]
若还有问题另提
