### ISSUE TITLE
vue-cli2中打包后theme-colors.css中rgba值丢失

### ISSUE THREAD

**Issue by 781499682ll** [hzsrc/webpack-theme-color-replacer#66]
webpack: 3.6.0  
css: less  
![image](https://user-images.githubusercontent.com/43060542/108796774-7f9d7f00-75c4-11eb-8d0e-fd8f1b77401d.png)
npm run dev正常

**Comment by 781499682ll** [comment]
似乎和 OptimizeCSSPlugin 有冲突我把这个关了，rgb值就有了

**Comment by 781499682ll** [comment]
找到原因了  
css在经过OptimizeCSSPlugin压缩之后，自动去除了rgb之间的空格  
而我在matchColors里只填了带空格的rgb值  
导致build后未匹配上对应的rgb

**Comment by 781499682ll** [comment]
作者大佬能否考虑优化下这个场景🐶

**Comment by hzsrc** [comment]
已兼容：matchColors里带空格。谢谢！
