### ISSUE TITLE
封装了一个组件  只有第一次进入页面的时候会触发换色 F5 刷新后无效

### ISSUE THREAD

**Issue by zhou1591** [hzsrc/webpack-theme-color-replacer#69]
大佬 你好 请教问题 挺急的 希望看到回答下
1.vue文件为什么要在 export default 外边先client.changer.changeColor(options, Promise) 一下
2 为什么我在created 或者mounted 里边 执行 不起作用 或者说 我没有进入文件就执行这个方法 然后用颜色选择器更改 不生效 我看F12 里边 style 标签里边是html模板
3 只能某个页面用 提前调用一下你demo 里边的方法嘛？ 可以全局配置嘛， 我在main.js或者app.vue 里边不生效 也是生成的html模板
4 我是封装的组件 后台管理模板那种，我在头部加了颜色选择器然后我初始化调用了方法，第一次进入页面是可以的 ，但是我F5 刷新后 再去更换颜色就不生效了 是为什么
万分火急 希望大佬或者好心人看到解答一下 谢谢

**Comment by hzsrc** [comment]
https://github.com/hzsrc/vue-element-ui-scaffold-webpack4/tree/webpack4
建议参考下这个样例代码。

补充说明：
1、在任何你希望切换主题色的时候，调用 client.changer.changeColor(options, Promise) 。一般在界面显示前调用。
2、可重复调用changeColor。
3、组件里面不要调用changeColor，而是entry的入口。这个插件是全局的，以webpack的entry为边界，一个entry里替换一次。

**Comment by zhou1591** [comment]
> https://github.com/hzsrc/vue-element-ui-scaffold-webpack4/tree/webpack4
> 建议参考下这个样例代码。
> 
> 补充说明：
> 1，在任何你希望切换主题色的时候，调用client.changer.changeColor（options，Promise）。一般在界面显示前调用
> 。2，可重复调用changeColor。3
> ，组件里面不要调用changeColor，而是在整体项目entry的入口调用。这个插件是一体的，以webpack的entry为边界，一个entry里替换一次。

大佬  麻烦你看着这个  我得入口是main.js  然后我这么做的 但是页面没有反应  ,求助！
![image](https://user-images.githubusercontent.com/39522200/114333932-17a6f600-9b7c-11eb-963a-d2cb43b52617.png)

```
 async function changeThemeColor (newColor) {
  const options = {
    newColors: forElementUI.getElementUISeries(newColor)
  }
  await client.changer.changeColor(options, Promise)
  localStorage.setItem('theme_color', newColor)
}
const themeColor = localStorage.getItem('theme_color') || '#409EFF'
changeThemeColor(themeColor).then(res => {
  new Vue({
    router,
    store,
    render: h => h(App)
  }).$mount('#app')
})

```

**Comment by zhou1591** [comment]
async function changeThemeColor (newColor) {
  const options = {
    newColors: forElementUI.getElementUISeries(newColor)
  }
  await client.changer.changeColor(options, Promise)
  localStorage.setItem('theme_color', newColor)
}
const themeColor = localStorage.getItem('theme_color') || '#409EFF'
changeThemeColor(themeColor).then(res => {
  new Vue({
    router,
    store,
    render: h => h(App)
  }).$mount('#app')
})

**Comment by hzsrc** [comment]
http://test.hz300.com/webpack4/#/
请对比参考示例代码




------------------&nbsp;Original message&nbsp;------------------
From: "zhou1591"; 
Sendtime: Monday, Apr 12, 2021 1:38 PM
To: "hzsrc/webpack-theme-color-replacer"; 
Cc: "5953107"; "Comment"; 
Subject: Re: [hzsrc/webpack-theme-color-replacer] 封装了一个组件  只有第一次进入页面的时候会触发换色 F5 刷新后无效 (#69)





 
async function changeThemeColor (newColor) {
 const options = {
 newColors: forElementUI.getElementUISeries(newColor)
 }
 await client.changer.changeColor(options, Promise)
 localStorage.setItem('theme_color', newColor)
 }
 const themeColor = localStorage.getItem('theme_color') || '#409EFF'
 changeThemeColor(themeColor).then(res =&gt; {
 new Vue({
 router,
 store,
 render: h =&gt; h(App)
 }).$mount('#app')
 })

**Comment by zhou1591** [comment]
> http://test.hz300.com/webpack4/#/ 请对比参考示例代码
> […](#)
> ------------------&nbsp;Original message&nbsp;------------------ From: "zhou1591"; Sendtime: Monday, Apr 12, 2021 1:38 PM To: "hzsrc/webpack-theme-color-replacer"; Cc: "5953107"; "Comment"; Subject: Re: [hzsrc/webpack-theme-color-replacer] 封装了一个组件 只有第一次进入页面的时候会触发换色 F5 刷新后无效 (#69) async function changeThemeColor (newColor) { const options = { newColors: forElementUI.getElementUISeries(newColor) } await client.changer.changeColor(options, Promise) localStorage.setItem('theme_color', newColor) } const themeColor = localStorage.getItem('theme_color') || '#409EFF' changeThemeColor(themeColor).then(res =&gt; { new Vue({ router, store, render: h =&gt; h(App) }).$mount('#app') }) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我把你  代码clone 下来了 然后把你代码里边所有 initThemeColor 都注释了 只留下了changeThemeColor  看你里边是颜色选择器用的这个changeThemeColor方法   是可以变色的

**Comment by zhou1591** [comment]
> http://test.hz300.com/webpack4/#/ 请对比参考示例代码
> […](#)
> ------------------&nbsp;Original message&nbsp;------------------ From: "zhou1591"; Sendtime: Monday, Apr 12, 2021 1:38 PM To: "hzsrc/webpack-theme-color-replacer"; Cc: "5953107"; "Comment"; Subject: Re: [hzsrc/webpack-theme-color-replacer] 封装了一个组件 只有第一次进入页面的时候会触发换色 F5 刷新后无效 (#69) async function changeThemeColor (newColor) { const options = { newColors: forElementUI.getElementUISeries(newColor) } await client.changer.changeColor(options, Promise) localStorage.setItem('theme_color', newColor) } const themeColor = localStorage.getItem('theme_color') || '#409EFF' changeThemeColor(themeColor).then(res =&gt; { new Vue({ router, store, render: h =&gt; h(App) }).$mount('#app') }) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬  你不要嫌弃我菜......  我想问下 是不是因为我得css 是远程的 所以不行  我不熟到线上的代码是link 引入的css  还有我是vue-cli3的脚手架  我用你这个代码 同样试了以下  生成的style 标签里边 是html     你看  大佬
![image](https://user-images.githubusercontent.com/39522200/114512327-92027380-9c6b-11eb-9bd7-b4024f6317a7.png)

**Comment by zhou1591** [comment]
加个wx呗 15032985110 @hzsrc

**Comment by hzsrc** [comment]
initThemeColor 就是设置初始颜色的啊，你去掉它当然就没设置咯

**Comment by zhou1591** [comment]
> initThemeColor 就是设置初始颜色的啊，你去掉它当然就没设置咯

是这样的  大哥  我加上 也是上边的样子 里边都是html  没有css

**Comment by zhou1591** [comment]
然后我调用change  方法的时候 里边的html 会变格式  但是没有css

**Comment by zhou1591** [comment]
大哥 你看我发的那个图 @hzsrc

**Comment by hzsrc** [comment]
link 引入的css无法识别的。可以配置externalCssFiles：
`externalCssFiles: ['./node_modules/element-ui/lib/theme-chalk/index.css'], // optional, String or string array. Set external css files (such as cdn css) to extract colors.
 `
来帮助它识别。

**Comment by hzsrc** [comment]
样式里是html，是因为路径不对

**Comment by zhou1591** [comment]
啥路径 大哥 你终于回复我了  能详细说下不

**Comment by zhou1591** [comment]
是不是打包的那个路径

![image](https://user-images.githubusercontent.com/39522200/114519563-1d333780-9c73-11eb-8a6b-1a51c64fc5fc.png)

是这个么

**Comment by zhou1591** [comment]
我们这个是 项目部署后打包后生成很多css  和js  会被上传到oss 里边 然后线上的项目 会引入这些上传的css和js @hzsrc

**Comment by zhou1591** [comment]
好的谢谢大哥搞定了
