### ISSUE TITLE
extractColors.js:6  在编译时会报错

### ISSUE THREAD

**Issue by ishouhu** [hzsrc/webpack-theme-color-replacer#7]
var trimReg = /^\s+|[\}\s]+$|(?<=,)\s+/g; 
这句正则编译时报错，
SyntaxError: Invalid regular expression: /^\s+|[\}\s]+$|(?<=,)\s+/: Invalid group
我查了下，是说webpack编译js正则时不支持后行断言。 有办法解决这个么？
我的正则不太好，不知道怎么改

**Comment by hzsrc** [comment]
没碰到过，是不是你的node版本太低了？

**Comment by ishouhu** [comment]
有可能是的。我用同事的电脑编译时没有出现这个问题




------------------ 原始邮件 ------------------
发件人: "hz"<notifications@github.com>;
发送时间: 2019年4月12日(星期五) 下午4:44
收件人: "hzsrc/webpack-theme-color-replacer"<webpack-theme-color-replacer@noreply.github.com>;
抄送: "一"<541598907@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [hzsrc/webpack-theme-color-replacer] extractColors.js:6  在编译时会报错 (#7)




没碰到过，是不是你的node版本太低了？

**Comment by hzsrc** [comment]
Node 7及以下 不支持后行断言，爲提高兼容性，新版本已更改正則的寫法。謝謝反饋
