### ISSUE TITLE
一级路由里边 生成的css 是html  并且更改不生效  大佬请进 ，万分火急求助！！！！

### ISSUE THREAD

**Issue by zhou1591** [hzsrc/webpack-theme-color-replacer#70]
我这有一个后台管理系统

这里是封装了一个组件代码如下
![image](https://user-images.githubusercontent.com/39522200/114133789-2e113f80-9939-11eb-8657-6cbb80e046b8.png)
```
<template>
  <ElColorPicker
    class="layout-theme__color"
    popper-class="layout-theme-dropdown"
    v-model="color"
    @change="changeThemeColor"
    size="mini"
    :predefine="predeColorList">
  </ElColorPicker>
</template>

<script>
import client from 'webpack-theme-color-replacer/client'
import forElementUI from 'webpack-theme-color-replacer/forElementUI'
/**
 * @description: 更换主题色
 * @param {*} newColor
 */
async function changeThemeColor (newColor) {
  const options = {
    newColors: forElementUI.getElementUISeries(newColor)
  }
  await client.changer.changeColor(options, Promise)
  localStorage.setItem('theme_color', newColor)
}
const themeColor = localStorage.getItem('theme_color') || '#409EFF'
changeThemeColor(themeColor)
export default {
  data () {
    return {
      predeColorList: [// 预留色
        '#ff4500',
        '#ff8c00',
        '#ffd700',
        '#90ee90',
        '#00ced1',
        '#1e90ff',
        '#c71585'
      ],
      color: localStorage.getItem('theme_color') || '#409EFF' // 当前选中色
    }
  },
  methods: {
    changeThemeColor
  }
}
</script>

```

然后我内容部分是一个二级路由
主题色不生效

css 里边是这个

![image](https://user-images.githubusercontent.com/39522200/114134270-0a9ac480-993a-11eb-9814-4093ec326163.png)

颜色选择器调用change 是这个
![image](https://user-images.githubusercontent.com/39522200/114134352-2e5e0a80-993a-11eb-8667-9854c2e8dd7b.png)

在本地折腾得到的结论是 只有在对应的二级路由页面的  export default 外边初始化 比如
![image](https://user-images.githubusercontent.com/39522200/114134872-09b66280-993b-11eb-8db5-7239a8bacf82.png)

 才生效  那我这种在一级路由组件初始化的不行吗？  能不能全局初始化以下  我在app.vue  main.js 都不行  或者我需要每个页面都加一个初始化？  感觉不太合理的样子 大佬能帮助一下吗

**Comment by hzsrc** [comment]
组件里面不要调用changeColor（除非是入口组件），而是在entry的入口调用。这个插件替换主题色是全局的，整个项目的主题色都包含在内；调用以webpack的entry为边界，一个entry里调用一次替换主题色。

**Comment by Zachary-zm** [comment]
不好意思，没有理解，能请问下后续怎么解决的吗？ 放到main里面也不行，但是会偶然可以，很奇怪
