### ISSUE TITLE
Vue项目设置了publicPath情况下，该插件更换主题失败

### ISSUE THREAD

**Issue by godchao** [hzsrc/webpack-theme-color-replacer#71]
您好！
在Vue项目的vue.config.js中设置了publicPath之后，该插件更换主题失效，参数如下：

1. publicPath：/ui/
2. themePluginOption ->  fileName :  'css/theme-colors-[contenthash:8].css'

经排查，系列信息如下：

1. 切换主题后，加载的主题颜色CSS路径为：http://localhost:8000/css/theme-colors-945254a9.css ，这个路径是加载不到css内容的。
2. 我在浏览器中访问：http://localhost:8000/ui/css/theme-colors-945254a9.css 路径时，却是具有文件的，证明文件生成是成功的，但在加载文件时，路径忽略掉了上述的publicPath参数。
3. vue.config.js配置文件中的 publicPath 参数也将与 webpack中的 output.publicPath 参数一致。

**Comment by hzsrc** [comment]
有个changeUrl的回调函数，可解决。

**Comment by hzsrc** [comment]
也有`fileName`选项呀， `fileName: 'css/theme-colors-[contenthash:8].css'`只是默认文件名

**Comment by pangchao21** [comment]
> 您好！ 在Vue项目的vue.config.js中设置了publicPath之后，该插件更换主题失效，参数如下：
> 
> 1. publicPath：/ui/
> 2. themePluginOption ->  fileName :  'css/theme-colors-[contenthash:8].css'
> 
> 经排查，系列信息如下：
> 
> 1. 切换主题后，加载的主题颜色CSS路径为：http://localhost:8000/css/theme-colors-945254a9.css ，这个路径是加载不到css内容的。
> 2. 我在浏览器中访问：http://localhost:8000/ui/css/theme-colors-945254a9.css 路径时，却是具有文件的，证明文件生成是成功的，但在加载文件时，路径忽略掉了上述的publicPath参数。
> 3. vue.config.js配置文件中的 publicPath 参数也将与 webpack中的 output.publicPath 参数一致。

你好，我也是遇到你这个问题，请问你解决了吗？可否共享下解决方案？万分感谢你
