### ISSUE TITLE
electron 打包后无法切换主题 Cannot set property '__theme_COLOR_cfg' of undefined

### ISSUE THREAD

**Issue by daystory** [hzsrc/webpack-theme-color-replacer#72]
<img width="1180" alt="截屏2021-04-10 上午1 29 20" src="https://user-images.githubusercontent.com/15036119/114218977-aceb9400-999c-11eb-8c39-639e9e4b3cf6.png">

**Comment by hzsrc** [comment]
如何重现？
估计还是配置上的问题，请仔细看下首页文档尝试下。

**Comment by daystory** [comment]
配置在开发模式下是没有问题的，我查看了开发模式和打包模式下的window对象，打包模式下__theme_COLOR_cfg没有设置成功，
开发模式
<img width="633" alt="截屏2021-04-10 下午10 11 50" src="https://user-images.githubusercontent.com/15036119/114272824-43c25a00-9a4a-11eb-91b0-ec70f55ad75c.png">
打包模式
<img width="817" alt="截屏2021-04-10 下午10 09 42" src="https://user-images.githubusercontent.com/15036119/114272845-55a3fd00-9a4a-11eb-9123-7968168437ce.png">


问题应该出在设置window对象上

**Comment by daystory** [comment]
修改代码为如下所示，程序正常运行
<img width="967" alt="截屏2021-04-10 下午11 07 43" src="https://user-images.githubusercontent.com/15036119/114274608-e16d5780-9a51-11eb-9a0b-45dd5b0dd8a9.png">

**Comment by hzsrc** [comment]
this不能取到window吗？之前有人说ssr模式下不能用，所以改this了

**Comment by hzsrc** [comment]
@daystory 你先用1.3.16版本解决问题，我后面处理下

**Comment by hzsrc** [comment]
已提交
