### ISSUE TITLE
src/Handler.js:70  

### ISSUE THREAD

**Issue by Red-xiaoshami** [hzsrc/webpack-theme-color-replacer#76]
configJs = configJs + '(typeof window=='undefined'?global:window).__theme_COLOR_css=' + JSON.stringify(cssCode.replace(LineReg, '')) + ';\n'
报SyntaxError: Unexpected identifier

**Comment by Red-xiaoshami** [comment]
'(typeof window=='undefined'?global:window).__theme_COLOR_css='  两个''造成的，应该是"(typeof window=='undefined'?global:window).__theme_COLOR_css="吧

**Comment by kindredPP** [comment]
同问，希望作者尽快解决

**Comment by ZhuHeart** [comment]
+1，已经回退版本了

**Comment by activeThomas** [comment]
+1，这个版本的Handler确实存在问题，修改为：configJs = configJs + `'(typeof window=='undefined'?global:window).__theme_COLOR_css='` + JSON.stringify(cssCode.replace(LineReg, '')) + ';\n'就没问题了

**Comment by zhipenglin** [comment]
请作者尽快修改吧，同遇到这个问题

**Comment by hzsrc** [comment]
是的，修复了
