### ISSUE TITLE
能否将element主题中的另外四种情景色（信息，成功，警告，危险色）也加入到getElementUISeries方法里？

### ISSUE THREAD

**Issue by ishouhu** [hzsrc/webpack-theme-color-replacer#8]
因为更换主题的话，另外四种情境色也要跟着变，一个一个去写它们的浅色和深色比较麻烦，如果能和主题色一样能自动扩展开就好了

**Comment by hzsrc** [comment]
目前可以实现的。你可以把这四个颜色分别调用getElementUISeries，将得到到数组合并，传递给options。注意oldColors和newColors一一对应：

```js
  var options = {
    cssUrl: 'css/theme-colors.css',
    oldColors: getElementUISeries(color1).concat(getElementUISeries(color1)), // current colors array
    newColors: [你的数组] // new colors array
  }
  try {
    replacer.changer.changeColor(options)
  } catch (e) {
    console.error(e)
  }
```

**Comment by ishouhu** [comment]
嗯嗯，好的。 谢谢大神




------------------ 原始邮件 ------------------
发件人: "hz"<notifications@github.com>;
发送时间: 2019年4月12日(星期五) 下午4:42
收件人: "hzsrc/webpack-theme-color-replacer"<webpack-theme-color-replacer@noreply.github.com>;
抄送: "一"<541598907@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [hzsrc/webpack-theme-color-replacer] 能否将element主题中的另外四种情景色（信息，成功，警告，危险色）也加入到getElementUISeries方法里？ (#8)




目前可以实现的。你可以把这四个颜色分别调用getElementUISeries，将得到到数组合并，传递给options。注意oldColors和newColors一一对应：
   var options = {     cssUrl: 'css/theme-colors.css',     oldColors: getElementUISeries(color1).concat(getElementUISeries(color1)), // current colors array     newColors: [你的数组] // new colors array   }   try {     replacer.changer.changeColor(options)   } catch (e) {     console.error(e)   }
