### ISSUE TITLE
element-ui功能色在生产和开发环境下不一致

### ISSUE THREAD

**Issue by juetan** [hzsrc/webpack-theme-color-replacer#85]
作者你好，我在本地开发环境下修改了element-ui的功能色，在本地是正常的，但是打包之后发现少了功能色主色，悬浮色和点击色是正常的。
这是开发环境下的样式：
![image](https://user-images.githubusercontent.com/36595085/116051545-4c05d080-a6ab-11eb-825f-a2f2bc4bf433.png)
这是打包后的样式：
![image](https://user-images.githubusercontent.com/36595085/116051114-d4d03c80-a6aa-11eb-9925-a08a13a97641.png)

**Comment by juetan** [comment]
好像找到原因了，16进制的颜色如果是简写的话，写全会失效，例如#3C9写成#33CC99，我刚把全写改成简写，打包后的样式出现了样式。

**Comment by hzsrc** [comment]
#3C9这种格式我记得是支持的，回头我再看下

**Comment by hzsrc** [comment]
测过支持的。如果使用#3C9这样的，需要matchColors里面也包含
