### ISSUE TITLE
getCssString方法bug

### ISSUE THREAD

**Issue by pc-20184** [hzsrc/webpack-theme-color-replacer#86]
getCssString方法的请求地址应该用当前的域名+cssUrl，history模式在去掉#号后，请求地址应该为："http://www.domain/cssUrl"，而不是"http://www.domain/routerName/cssUrl"

**Comment by hzsrc** [comment]
不太明白说的意思。你可以用options.cssUrl 或 options.changeUrl自定义url地址。如果确定有bug欢迎PR
