### ISSUE TITLE
Handler.js is crashing on yarn start

### ISSUE THREAD

**Issue by luizsky10** [hzsrc/webpack-theme-color-replacer#87]
'(typeof window=='undefined'?global:window).__theme_COLOR_css=' + JSON.stringify(cssCode.replace(LineReg, '')) + ';\n'

I think '' should be replace to `` to avoid handler.js crashes the start script.

**Comment by hzsrc** [comment]
Yes, please upgrade to a new version

**Comment by luizsky10** [comment]
Thanks, it's worked!
