### ISSUE TITLE
getElementUISeries第一行判断写的有问题

### ISSUE THREAD

**Issue by flaginfo** [hzsrc/webpack-theme-color-replacer#9]
module.exports = function (colorStr) {
    **if (colorStr[0] = '#') colorStr = colorStr.slice(1)**
    var colors = ['#' + colorStr, varyColor.toNum3(colorStr).join(',')]
    for (var i = 0; i <= 9; i++)
        colors.push(varyColor.lighten(colorStr, Number((i / 10).toFixed(2))));
    colors.push(varyColor.rgba(colorStr, 0.1))
    colors.push(varyColor.rgba(colorStr, 0.2))
    return colors
}

第一行判断应该不是赋值语句而是判断语句使用 === 不然传入的颜色值如果没有#就会有问题
并且传入的字符串如果是常量会报错

**Comment by hzsrc** [comment]
是的，我修复一下
