### ISSUE TITLE
该插件与postcss-inline-svg冲突

### ISSUE THREAD

**Issue by williamChen26** [hzsrc/webpack-theme-color-replacer#92]
大佬您好，最近发现使用您开发的插件，发现与postcss-inline-svg插件冲突，postcss-inline-svg是用于引用 SVG 文件并使用 CSS 语法控制其属性。如果两个插件一起使用的话，会导致主题颜色修改无法起作用。

**Comment by williamChen26** [comment]
如颜色#2354f5，我要更换次颜色matchColor: [#2354f5......]，遇到index.css->background: center #2354F4 svg-load('../data/svg/sunOn.svg')时，会导致更换主题颜色不起作用

**Comment by williamChen26** [comment]
在打包提取css时，识别";"符号，根据它来切割代码。svg-load(...)会把url处理成base64字符，里面存在";"符号，其识别到了，导致出错
<img width="812" alt="F7E0D79A-57D7-4A1F-91DB-55A9A9D4C771" src="https://user-images.githubusercontent.com/86882889/126484188-e535c8dd-762d-4160-be51-b006b0ea62c6.png">

**Comment by hzsrc** [comment]
你好！已修复了，谢谢。
