### ISSUE TITLE
当使用background被指定多个背景层含有文件路径时会导致切换主题色失效

### ISSUE THREAD

**Issue by Sun79** [hzsrc/webpack-theme-color-replacer#93]
当使用类似以下含有文件路径的background样式时，会导致切换主题色失效：
```css
background: center / 80% no-repeat url(~@/assets/img/roster_bg.svg),
    linear-gradient(-45deg, @primary-color, @primary-5);
```
初步排查是由于图片等资源文件路径会存储在变量中，最后会通过拼接字符串的方式生成样式表，而该插件在提取主题色样式时会直接通过代码字符串提取，这就会导致提取的样式不正确。

![微信图片_20210721152347](https://user-images.githubusercontent.com/17243584/126448513-cf9a9be4-1af1-4c9f-896a-529a8fe30d1a.png)
![微信截图_20210721152412](https://user-images.githubusercontent.com/17243584/126448539-5a7d994b-634d-4dce-b9b1-aa92a274f989.png)
![微信图片_20210721152458](https://user-images.githubusercontent.com/17243584/126448550-5533251e-c808-49c0-a62c-1310bf984913.png)

暂时可以不使用background简写或在两个元素上设置背景解决此问题。

本人对webpack不太熟悉，不知是否可以通过从生成后样式表字符串或文件提取样式的方式解决此问题，如有错误恳请指正，谢谢。

**Comment by hzsrc** [comment]
问下这个项目css-loader用的哪个版本？除了css-loader之外还有用其他插件会修改css-loader生成的代码吗？
css-loader生成的代码修改，可能没有好办法解决。
最方便的办法还是不要把主题色相关颜色和url写在一个属性里，比如分开写backgroud-image和background-color

**Comment by Sun79** [comment]
我就是使用您的测试代码测试的，css-loader在处理url时应该默认就会生成占位的变量，现在也就在需要同时设置`linear-gradient`和背景图片时比较麻烦，遇到的概率比较小，我会关闭此问题，感谢您的解答，谢谢。
https://github.com/webpack-contrib/css-loader/blob/7ec58314f1b833da35b9a32db89697b597519dc1/src/plugins/postcss-url-parser.js#L414
