### ISSUE TITLE
changeUrl可否作为一个参数项进行初始化配置

### ISSUE THREAD

**Issue by charlesyxh** [hzsrc/webpack-theme-color-replacer#96]
![image](https://user-images.githubusercontent.com/4962639/138068483-3dd4542f-f0ee-407d-b9df-467c5f1907ed.png)
在这其实更期望return的url可以在初始化作为一个options参数项配置进去

**Comment by hzsrc** [comment]
不太明白你说的意思。或者你可以提交一个PullRequest？
