### ISSUE TITLE
publicPath 配置问题

### ISSUE THREAD

**Issue by pangchao21** [hzsrc/webpack-theme-color-replacer#97]
在vue.config.js文件里面如果设置了publicPath，动态换肤会失效，请问该怎么处理呢

**Comment by pangchao21** [comment]
![image](https://user-images.githubusercontent.com/25843968/143018094-9e36a29c-3534-45e6-b79d-1ecc47047f28.png
作者，您好。我通过这个changeUrl的回调函数去写入路劲，但是cssUrl这个参数是个undefined

**Comment by pangchao21** [comment]
![image](https://user-images.githubusercontent.com/25843968/143018881-f26feaba-adaa-437d-99b5-321b4f1ef4e1.png)
有一段还是重复了，正确怎么写的呢

**Comment by pangchao21** [comment]
![image](https://user-images.githubusercontent.com/25843968/143020591-0c9b2094-cfd8-4dc7-8610-8b52ddabd9c1.png)
这个是我的配置

**Comment by Mcleanpoets** [comment]
> ![image](https://user-images.githubusercontent.com/25843968/143020591-0c9b2094-cfd8-4dc7-8610-8b52ddabd9c1.png) 这个是我的配置

你好，这个问题你有处理结果吗？我也出现这个问题，publicPath 是 '/'， cssUrl没问题，publicPath 如果是二级目录，cssUrl 就返回 undefined

**Comment by pangchao21** [comment]
![image](https://user-images.githubusercontent.com/25843968/144834034-34f5abb0-ff88-45a9-bb37-c7bb3a62ab78.png)
要重写下这个changeColor的回调方法

**Comment by Mcleanpoets** [comment]
> ![image](https://user-images.githubusercontent.com/25843968/144834034-34f5abb0-ff88-45a9-bb37-c7bb3a62ab78.png) 要重写下这个changeColor的回调方法

![image](https://user-images.githubusercontent.com/28701169/144947481-61321605-3555-4796-9284-8b5de4469b85.png)
![image](https://user-images.githubusercontent.com/28701169/144947515-99a1aee9-1ba9-48d4-bf18-96f0ce6b186b.png)
![image](https://user-images.githubusercontent.com/28701169/144947549-dd3b82bf-dfd3-4ee0-b930-cb8e5479d1a3.png)
![image](https://user-images.githubusercontent.com/28701169/144947569-9c098d5e-73ce-4cba-b7a0-da0760c0c62c.png)
![image](https://user-images.githubusercontent.com/28701169/144947716-dbddeb4b-3746-49aa-95fc-cb7b1a06fd59.png)
changeUrl这个回调重写后，打包后，还是cssUrl返回 undefined，如果BASE_URL 配置的是'/'打包之后就没问题

**Comment by pangchao21** [comment]
![image](https://user-images.githubusercontent.com/25843968/144953411-4a3fdfd4-744f-4ce8-bcfc-85922a88a11f.png)
![image](https://user-images.githubusercontent.com/25843968/144953474-2395615a-ef20-4916-9231-3e3e421f528f.png)
这两个配置改一下

**Comment by Mcleanpoets** [comment]
> ![image](https://user-images.githubusercontent.com/25843968/144953411-4a3fdfd4-744f-4ce8-bcfc-85922a88a11f.png) ![image](https://user-images.githubusercontent.com/25843968/144953474-2395615a-ef20-4916-9231-3e3e421f528f.png) 这两个配置改一下
![image](https://user-images.githubusercontent.com/28701169/144954536-71f9ab68-dd8a-4b62-8aba-7acd917bd8b4.png)


我的脑子呀，忘记这块的判断了，谢啦，搞定了

**Comment by hzsrc** [comment]
所以是配置问题吗？

**Comment by vocoWone** [comment]
> ![image](https://user-images.githubusercontent.com/25843968/144953411-4a3fdfd4-744f-4ce8-bcfc-85922a88a11f.png) ![image](https://user-images.githubusercontent.com/25843968/144953474-2395615a-ef20-4916-9231-3e3e421f528f.png) 这两个配置改一下

请问是怎么解决的呢？我在项目中配置了assetPrefix，客户端引入css时也出现了undefined的情况
